
import java.util.Set;
import javax.swing.JOptionPane;
import model.bean.Armazenamento;
import model.bean.Fonte;
import model.bean.Memoria;
import model.bean.PlacaExpansao;
import model.bean.Cliente;
import model.bean.PlacaMae;
import model.bean.Processador;
import model.dao.ArmazenamentoDAO;
import model.dao.FonteDAO;
import model.dao.MemoriaDAO;
import model.dao.PlacaExpansaoDAO;
import model.dao.PlacaMaeDAO;
import model.dao.ProcessadorDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Avell G1511 FIRE V3
 */
public class CadastroDePecas extends javax.swing.JFrame {
    Cliente cli = new Cliente();
    /**
     * Creates new form CadastroDePecas
     */
    public CadastroDePecas() {
        initComponents();        
    }
    
    public CadastroDePecas(Cliente cliente){
        initComponents();
                
        this.cli = cliente;
        setTextFields();
    }

    public void setTextFields(){
        jblUser.setText(this.cli.getNome());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadPecas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtabbedOptions = new javax.swing.JTabbedPane();
        jpanelFonte = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtModeloFonte = new javax.swing.JTextField();
        txtMarcaFonte = new javax.swing.JTextField();
        txtPotenciaFonte = new javax.swing.JTextField();
        txtCertificadoFonte = new javax.swing.JTextField();
        btnSalvarFonte = new javax.swing.JButton();
        jpanelArmazenamento = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSalvarArmazenamento = new javax.swing.JButton();
        txtModeloArmazenamento = new javax.swing.JTextField();
        txtMarcaArmazenamento = new javax.swing.JTextField();
        txtCapacidadeArmazenamento = new javax.swing.JTextField();
        txtCacheArmazenamento = new javax.swing.JTextField();
        txtTaxaTransArmazenamento = new javax.swing.JTextField();
        jpanelPlacaMae = new javax.swing.JPanel();
        jlblPlacaMae = new javax.swing.JLabel();
        txtMarcaPlacaMae = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmodeloPlacamae = new javax.swing.JTextField();
        txtNrSlotsPlacamae = new javax.swing.JTextField();
        txtMemoriaSuportada = new javax.swing.JTextField();
        txtConsumoEnergia = new javax.swing.JTextField();
        txtSocketPlacaMae = new javax.swing.JTextField();
        txtLimiteMemoriaSuportada = new javax.swing.JTextField();
        btnSalvarPlacaMae = new javax.swing.JButton();
        jpanelProcessador = new javax.swing.JPanel();
        txtMarcaProcessador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNrNucleo = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtNrThread = new javax.swing.JTextField();
        txtFrequencia = new javax.swing.JTextField();
        txtCache = new javax.swing.JTextField();
        txtSocket = new javax.swing.JTextField();
        btnSalvarProcessador = new javax.swing.JButton();
        lblMarcaProc2 = new javax.swing.JLabel();
        jpanelMemoria = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnSalvarMemoria = new javax.swing.JButton();
        txtModeloMemoria = new javax.swing.JTextField();
        txtMarcaMemoria = new javax.swing.JTextField();
        txtTipoMemoria = new javax.swing.JTextField();
        txtFreqMemoria = new javax.swing.JTextField();
        txtTamanhoMemoria = new javax.swing.JTextField();
        jpanelPlacaExpansao = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNomePE = new javax.swing.JTextField();
        txtMarcaPE = new javax.swing.JTextField();
        txtNucleoCUDAPE = new javax.swing.JTextField();
        txtFrequenciaPE = new javax.swing.JTextField();
        txtMemoriaPE = new javax.swing.JTextField();
        txtConsumoPE = new javax.swing.JTextField();
        btnSalvarPE = new javax.swing.JButton();
        jblUser = new javax.swing.JLabel();
        jblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadPecas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCadPecas.setText("Cadastro de Peças");

        jLabel1.setText("Tipo de cadastro:");

        jLabel25.setText("Modelo:");

        jLabel26.setText("Marca:");

        jLabel27.setText("Potência:");

        jLabel28.setText("Certificado:");

        btnSalvarFonte.setText("Salvar");
        btnSalvarFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFonteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelFonteLayout = new javax.swing.GroupLayout(jpanelFonte);
        jpanelFonte.setLayout(jpanelFonteLayout);
        jpanelFonteLayout.setHorizontalGroup(
            jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFonteLayout.createSequentialGroup()
                .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelFonteLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModeloFonte)
                            .addComponent(txtMarcaFonte)
                            .addComponent(txtPotenciaFonte)
                            .addComponent(txtCertificadoFonte, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(jpanelFonteLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnSalvarFonte)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jpanelFonteLayout.setVerticalGroup(
            jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFonteLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtModeloFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtMarcaFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtPotenciaFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelFonteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtCertificadoFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnSalvarFonte)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Fonte", jpanelFonte);

        jLabel29.setText("Modelo:");

        jLabel30.setText("Marca:");

        jLabel31.setText("Capacidade:");

        jLabel32.setText("Cache:");

        jLabel33.setText("Taxa de transferência:");

        btnSalvarArmazenamento.setText("Salvar");
        btnSalvarArmazenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarArmazenamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelArmazenamentoLayout = new javax.swing.GroupLayout(jpanelArmazenamento);
        jpanelArmazenamento.setLayout(jpanelArmazenamentoLayout);
        jpanelArmazenamentoLayout.setHorizontalGroup(
            jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelArmazenamentoLayout.createSequentialGroup()
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelArmazenamentoLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModeloArmazenamento)
                            .addComponent(txtMarcaArmazenamento)
                            .addComponent(txtCapacidadeArmazenamento)
                            .addComponent(txtCacheArmazenamento)
                            .addComponent(txtTaxaTransArmazenamento, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                    .addGroup(jpanelArmazenamentoLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnSalvarArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jpanelArmazenamentoLayout.setVerticalGroup(
            jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelArmazenamentoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtModeloArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtMarcaArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtCapacidadeArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtCacheArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtTaxaTransArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSalvarArmazenamento)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Armazenamento", jpanelArmazenamento);

        jlblPlacaMae.setText("Marca da placa mãe:");

        jLabel8.setText("Modelo da placa mãe:");

        jLabel9.setText("Número de slots:");

        jLabel10.setText("Tipo de Memória suportada:");

        jLabel11.setText("Consumo de energia:");

        jLabel12.setText("Socket da placa mãe:");

        jLabel13.setText("Limite de memória suportada:");

        txtMemoriaSuportada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemoriaSuportadaActionPerformed(evt);
            }
        });

        txtConsumoEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumoEnergiaActionPerformed(evt);
            }
        });

        btnSalvarPlacaMae.setText("Salvar");
        btnSalvarPlacaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPlacaMaeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelPlacaMaeLayout = new javax.swing.GroupLayout(jpanelPlacaMae);
        jpanelPlacaMae.setLayout(jpanelPlacaMaeLayout);
        jpanelPlacaMaeLayout.setHorizontalGroup(
            jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPlacaMaeLayout.createSequentialGroup()
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelPlacaMaeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jlblPlacaMae))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMarcaPlacaMae, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtmodeloPlacamae)
                            .addComponent(txtNrSlotsPlacamae)
                            .addComponent(txtMemoriaSuportada)
                            .addComponent(txtConsumoEnergia)
                            .addComponent(txtSocketPlacaMae)
                            .addComponent(txtLimiteMemoriaSuportada)))
                    .addGroup(jpanelPlacaMaeLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnSalvarPlacaMae)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jpanelPlacaMaeLayout.setVerticalGroup(
            jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPlacaMaeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPlacaMae)
                    .addComponent(txtMarcaPlacaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtmodeloPlacamae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNrSlotsPlacamae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMemoriaSuportada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtConsumoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSocketPlacaMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLimiteMemoriaSuportada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnSalvarPlacaMae)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Placa Mãe", jpanelPlacaMae);

        jpanelProcessador.setToolTipText("");

        txtMarcaProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaProcessadorActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de núcleos:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Número de thread:");

        jLabel5.setText("Frequência:");

        jLabel6.setText("Cache:");

        jLabel7.setText("Socket processador:");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        btnSalvarProcessador.setText("Salvar");
        btnSalvarProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProcessadorActionPerformed(evt);
            }
        });

        lblMarcaProc2.setText("Marca do processador:");

        javax.swing.GroupLayout jpanelProcessadorLayout = new javax.swing.GroupLayout(jpanelProcessador);
        jpanelProcessador.setLayout(jpanelProcessadorLayout);
        jpanelProcessadorLayout.setHorizontalGroup(
            jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelProcessadorLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(lblMarcaProc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMarcaProcessador, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(txtNrNucleo)
                    .addComponent(txtModelo)
                    .addComponent(txtNrThread)
                    .addComponent(txtFrequencia)
                    .addComponent(txtCache)
                    .addComponent(txtSocket)
                    .addGroup(jpanelProcessadorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarProcessador)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jpanelProcessadorLayout.setVerticalGroup(
            jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelProcessadorLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaProc2)
                    .addComponent(txtMarcaProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNrNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNrThread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSocket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSalvarProcessador)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Processador", jpanelProcessador);

        jLabel20.setText("Modelo:");

        jLabel21.setText("Marca:");

        jLabel22.setText("Tipo:");

        jLabel23.setText("Frequência de memória:");

        jLabel24.setText("Tamanho:");

        btnSalvarMemoria.setText("Salvar");
        btnSalvarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMemoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelMemoriaLayout = new javax.swing.GroupLayout(jpanelMemoria);
        jpanelMemoria.setLayout(jpanelMemoriaLayout);
        jpanelMemoriaLayout.setHorizontalGroup(
            jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtModeloMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMarcaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFreqMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTamanhoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnSalvarMemoria)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jpanelMemoriaLayout.setVerticalGroup(
            jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMemoriaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtModeloMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtTipoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtFreqMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamanhoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(37, 37, 37)
                .addComponent(btnSalvarMemoria)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Memória", jpanelMemoria);

        jLabel14.setText("Nome:");

        jLabel15.setText("Marca:");

        jLabel16.setText("Núcleos CUDA:");

        jLabel17.setText("Frequência CORE:");

        jLabel18.setText("Memoria:");

        jLabel19.setText("Consumo:");

        btnSalvarPE.setText("Salvar");
        btnSalvarPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelPlacaExpansaoLayout = new javax.swing.GroupLayout(jpanelPlacaExpansao);
        jpanelPlacaExpansao.setLayout(jpanelPlacaExpansaoLayout);
        jpanelPlacaExpansaoLayout.setHorizontalGroup(
            jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPlacaExpansaoLayout.createSequentialGroup()
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelPlacaExpansaoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomePE)
                            .addComponent(txtMarcaPE)
                            .addComponent(txtNucleoCUDAPE)
                            .addComponent(txtFrequenciaPE)
                            .addComponent(txtMemoriaPE)
                            .addComponent(txtConsumoPE, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                    .addGroup(jpanelPlacaExpansaoLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnSalvarPE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jpanelPlacaExpansaoLayout.setVerticalGroup(
            jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPlacaExpansaoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNomePE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMarcaPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNucleoCUDAPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtFrequenciaPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMemoriaPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlacaExpansaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtConsumoPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnSalvarPE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jtabbedOptions.addTab("Placa de Expansão", jpanelPlacaExpansao);

        jblUser.setText("User");

        jblTime.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtabbedOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(lblCadPecas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblCadPecas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jblUser)
                        .addGap(9, 9, 9)
                        .addComponent(jblTime)))
                .addGap(18, 18, 18)
                .addComponent(jtabbedOptions)
                .addContainerGap())
        );

        jtabbedOptions.getAccessibleContext().setAccessibleName("Processador");
        jblTime.getAccessibleContext().setAccessibleName("Time");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaProcessadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaProcessadorActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnSalvarProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProcessadorActionPerformed
            
            JOptionPane criadocomsucesso = new JOptionPane("Processador cadastrado com sucesso.");
            
            Processador proc = new Processador();
            ProcessadorDAO procDAO = new ProcessadorDAO();
            proc.setMarca(txtMarcaProcessador.getText());
            proc.setNumNucleos(Integer.parseInt(txtNrNucleo.getText()));
            proc.setModelo(txtModelo.getText());
            proc.setNumThread(Integer.parseInt(txtNrThread.getText()));
            proc.setFrequenciaProcessador(Float.parseFloat(txtFrequencia.getText()));
            proc.setCacheProcessador(Integer.parseInt(txtCache.getText()));
            proc.setSocketProcessador(txtSocket.getText());
            
            procDAO.insert(proc);
            JOptionPane.showMessageDialog(criadocomsucesso, "Processador cadastrado com sucesso.");
            
            limpaproc();
        
            
            
    }//GEN-LAST:event_btnSalvarProcessadorActionPerformed

    private void txtMemoriaSuportadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemoriaSuportadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemoriaSuportadaActionPerformed

    private void txtConsumoEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumoEnergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumoEnergiaActionPerformed

    private void btnSalvarFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFonteActionPerformed
            
            JOptionPane criadocomsucesso = new JOptionPane("Fonte cadastrada com sucesso.");
            
            Fonte fonte = new Fonte();
            FonteDAO fonteDAO = new FonteDAO();            
            fonte.setModelo(txtModeloFonte.getText());            
            fonte.setMarca((txtMarcaFonte.getText()));            
            fonte.setPotencia(Integer.parseInt(txtPotenciaFonte.getText())); 
            fonte.setCertificado(txtCertificadoFonte.getText());            
            fonteDAO.save(fonte);
            JOptionPane.showMessageDialog(criadocomsucesso, "Fonte cadastrada com sucesso.");
            
            limpafonte();
    }//GEN-LAST:event_btnSalvarFonteActionPerformed

    private void btnSalvarPlacaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPlacaMaeActionPerformed
            
        
            JOptionPane criadocomsucesso = new JOptionPane("Placa mae cadastrada com sucesso.");            
            PlacaMae motherboard = new PlacaMae();
            PlacaMaeDAO motherboardDAO = new PlacaMaeDAO(); 
            
            motherboard.setModelo(txtmodeloPlacamae.getText());
            motherboard.setMarca(txtMarcaPlacaMae.getText());
            motherboard.setNrSlot(Integer.parseInt(txtNrSlotsPlacamae.getText()));
            motherboard.setTipoMemoria(txtTipoMemoria.getText());
            motherboard.setConsumoPlacamae(Integer.parseInt(txtConsumoEnergia.getText()));
            motherboard.setSocket(txtSocketPlacaMae.getText());
            motherboard.setLimitacaoMemoriaPlacaMae(Integer.parseInt(txtLimiteMemoriaSuportada.getText()));       
            
                     
            motherboardDAO.save(motherboard);
            JOptionPane.showMessageDialog(criadocomsucesso, "Placa mae cadastrada com sucesso.");
            
            limpaplacamae();
    }//GEN-LAST:event_btnSalvarPlacaMaeActionPerformed

    private void btnSalvarArmazenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarArmazenamentoActionPerformed
            
            JOptionPane criadocomsucesso = new JOptionPane("Unidade de Armazenamento cadastrada com sucesso.");            
            Armazenamento hd = new Armazenamento();
            ArmazenamentoDAO hdDAO = new ArmazenamentoDAO(); 
            
            hd.setModelo(txtModeloArmazenamento.getText());
            hd.setMarca(txtMarcaArmazenamento.getText());
            hd.setCapacidade(Integer.parseInt(txtCapacidadeArmazenamento.getText()));
            hd.setCache(Integer.parseInt(txtCacheArmazenamento.getText()));
            hd.setTaxaTransferencia(Float.parseFloat(txtTaxaTransArmazenamento.getText()));             
            
                     
            hdDAO.insert(hd);
            JOptionPane.showMessageDialog(criadocomsucesso, "Unidade de Armazenamento cadastrada com sucesso.");
            
            limpaarmazenamento();
    }//GEN-LAST:event_btnSalvarArmazenamentoActionPerformed

    private void btnSalvarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMemoriaActionPerformed
            
            JOptionPane criadocomsucesso = new JOptionPane("Memoria cadastrada com sucesso.");            
            Memoria ram = new Memoria();
            MemoriaDAO ramDAO = new MemoriaDAO(); 
            
            ram.setModelo(txtModeloMemoria.getText());
            ram.setMarca(txtMarcaMemoria.getText());
            ram.setTipo(txtTipoMemoria.getText());
            ram.setFrequenciaMemoria(Float.parseFloat(txtFreqMemoria.getText()));
            ram.setTamanho(Integer.parseInt(txtTamanhoMemoria.getText()));
            
            ramDAO.insert(ram);
            JOptionPane.showMessageDialog(criadocomsucesso, "Memoria cadastrada com sucesso.");
            limpamemoria();
    }//GEN-LAST:event_btnSalvarMemoriaActionPerformed

    private void btnSalvarPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPEActionPerformed
            
            JOptionPane criadocomsucesso = new JOptionPane("Placa de expansao cadastrada com sucesso.");            
            PlacaExpansao pe = new PlacaExpansao();
            PlacaExpansaoDAO peDAO = new PlacaExpansaoDAO(); 
            
            pe.setNome(txtNomePE.getText());
            pe.setMarca(txtMarcaPE.getText());
            pe.setNucleosCUDA(Integer.parseInt(txtNucleoCUDAPE.getText()));
            pe.setFrequenciaCORE(Float.parseFloat(txtFrequenciaPE.getText()));
            pe.setMemoria(Integer.parseInt(txtMemoriaPE.getText()));
            pe.setConsumo(Integer.parseInt(txtConsumoPE.getText()));
            
            peDAO.insert(pe);
            JOptionPane.showMessageDialog(criadocomsucesso, "Placa de expansao cadastrada com sucesso.");
            limpaplacaexp();
        
    }//GEN-LAST:event_btnSalvarPEActionPerformed

    /**
     * 
     * 
     */
    
    public void limpafonte(){
        txtModeloFonte.setText("");
        txtMarcaFonte.setText("");
        txtPotenciaFonte.setText("");
        txtCertificadoFonte.setText("");
        txtModeloFonte.requestFocus();
    }
    public void limpaplacaexp(){
        txtNomePE.setText("");
        txtMarcaPE.setText("");
        txtNucleoCUDAPE.setText("");
        txtFrequenciaPE.setText("");
        txtMemoriaPE.setText("");
        txtConsumoPE.setText("");
        txtNomePE.requestFocus();    
    }
    
    public void limpaplacamae(){
        txtmodeloPlacamae.setText("");
        txtMarcaPlacaMae.setText("");
        txtNrSlotsPlacamae.setText("");
        txtMemoriaSuportada.setText("");
        txtConsumoEnergia.setText("");
        txtSocketPlacaMae.setText("");
        txtLimiteMemoriaSuportada.setText("");        
        txtMarcaPlacaMae.requestFocus();
    }
    public void limpaarmazenamento(){
        txtModeloArmazenamento.setText("");
        txtMarcaArmazenamento.setText("");
        txtCapacidadeArmazenamento.setText("");
        txtCacheArmazenamento.setText("");
        txtTaxaTransArmazenamento.setText("");
        txtModeloArmazenamento.requestFocus();
    }
    public void limpamemoria(){
        txtModeloMemoria.setText("");
        txtMarcaMemoria.setText("");
        txtTipoMemoria.setText("");
        txtFreqMemoria.setText("");
        txtTamanhoMemoria.setText("");
        txtModeloMemoria.requestFocus();
    }
    public void limpaproc(){
        txtCache.setText("");
        txtFrequencia.setText("");
        txtMarcaProcessador.setText("");
        txtSocket.setText("");
        txtModelo.setText("");
        txtNrNucleo.setText("");
        txtNrThread.setText("");        
        txtMarcaProcessador.requestFocus();    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarArmazenamento;
    private javax.swing.JButton btnSalvarFonte;
    private javax.swing.JButton btnSalvarMemoria;
    private javax.swing.JButton btnSalvarPE;
    private javax.swing.JButton btnSalvarPlacaMae;
    private javax.swing.JButton btnSalvarProcessador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jblTime;
    private javax.swing.JLabel jblUser;
    private javax.swing.JLabel jlblPlacaMae;
    private javax.swing.JPanel jpanelArmazenamento;
    private javax.swing.JPanel jpanelFonte;
    private javax.swing.JPanel jpanelMemoria;
    private javax.swing.JPanel jpanelPlacaExpansao;
    private javax.swing.JPanel jpanelPlacaMae;
    private javax.swing.JPanel jpanelProcessador;
    private javax.swing.JTabbedPane jtabbedOptions;
    private javax.swing.JLabel lblCadPecas;
    private javax.swing.JLabel lblMarcaProc2;
    private javax.swing.JTextField txtCache;
    private javax.swing.JTextField txtCacheArmazenamento;
    private javax.swing.JTextField txtCapacidadeArmazenamento;
    private javax.swing.JTextField txtCertificadoFonte;
    private javax.swing.JTextField txtConsumoEnergia;
    private javax.swing.JTextField txtConsumoPE;
    private javax.swing.JTextField txtFreqMemoria;
    private javax.swing.JTextField txtFrequencia;
    private javax.swing.JTextField txtFrequenciaPE;
    private javax.swing.JTextField txtLimiteMemoriaSuportada;
    private javax.swing.JTextField txtMarcaArmazenamento;
    private javax.swing.JTextField txtMarcaFonte;
    private javax.swing.JTextField txtMarcaMemoria;
    private javax.swing.JTextField txtMarcaPE;
    private javax.swing.JTextField txtMarcaPlacaMae;
    private javax.swing.JTextField txtMarcaProcessador;
    private javax.swing.JTextField txtMemoriaPE;
    private javax.swing.JTextField txtMemoriaSuportada;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModeloArmazenamento;
    private javax.swing.JTextField txtModeloFonte;
    private javax.swing.JTextField txtModeloMemoria;
    private javax.swing.JTextField txtNomePE;
    private javax.swing.JTextField txtNrNucleo;
    private javax.swing.JTextField txtNrSlotsPlacamae;
    private javax.swing.JTextField txtNrThread;
    private javax.swing.JTextField txtNucleoCUDAPE;
    private javax.swing.JTextField txtPotenciaFonte;
    private javax.swing.JTextField txtSocket;
    private javax.swing.JTextField txtSocketPlacaMae;
    private javax.swing.JTextField txtTamanhoMemoria;
    private javax.swing.JTextField txtTaxaTransArmazenamento;
    private javax.swing.JTextField txtTipoMemoria;
    private javax.swing.JTextField txtmodeloPlacamae;
    // End of variables declaration//GEN-END:variables
}
